### ISSUE TITLE
depth information

### ISSUE THREAD

**Issue by ad45675** [fnzhan/EMLight#21]
hi ,

i saw your code in data.py have ['depth'] term, but not in distribution_representation.py pkl's save para.
Is the 'depth' used in training? and how can i get the 'depth' information.

thanks!

**Comment by fnzhan** [comment]
You can remove the depth part, which doesn't bring clear improvement. I got the depth map by contacting the author of Laval indoor dataset.

**Comment by Lingstreasure** [comment]
Dear Zhan:
I found the GMlight used the depth value, but it seems that the code does't contain the corresponding part. Will you release the code later or I just missed some important part .

**Comment by fnzhan** [comment]
I include the depth part in a previous version, but remove it later as observing most users don't have access to the depth of Laval indoor dataset.
