### ISSUE TITLE
Why tone Fov image ?

### ISSUE THREAD

**Issue by jxl0131** [fnzhan/EMLight#23]
Hello!

I found that you use a TonemapHDR(..) function to tone your images in '\crop'  folder.
Is it mean that images in '\crop' are just cut from hdr, without any tone process ?

**Comment by fnzhan** [comment]
Hi, sorry for the late reply.
Yes, the images in \crop are HDR images, I got cropped hdr directly from the author of 'Deep Parametric Indoor Lighting Estimation'.
