### ISSUE TITLE
about supplementary file & daatset file structure

### ISSUE THREAD

**Issue by liuyuwan233** [fnzhan/EMLight#25]
Hi!
1. In the paper, you mentioned 'Detailed network structure of neural projector and the training settings are provided in the supplementary file.', but I can not fild the supplementary file. Would you like to tell me where is the supplementary file?

2. What's more, I tried to train my own dataset with your code for comparison, but I don't know the original file structure so I got some problems. Could you tell me the structure of the original file and the format of the images in the folder?

Thank you very much!

**Comment by jxl0131** [comment]
> Hi!
> 
>     1. In the paper, you mentioned 'Detailed network structure of neural projector and the training settings are provided in the supplementary file.', but I can not fild the supplementary file. Would you like to tell me where is the supplementary file?
> 
>     2. What's more, I tried to train my own dataset with your code for comparison, but I don't know the original file structure so I got some problems. Could you tell me the structure of the original file and the format of the images in the folder?
> 
> 
> Thank you very much!

Hi!

 I want follow EMLight's work, but i can't use LavalInDoor dataset, because professor Jean-François Lalonde told me that their server was broke down since bout 2 months ago. I wonder that what other dataset you want to use to train? 

Thanks!

**Comment by liuyuwan233** [comment]
> 

Hi!
I wanted to train my own dataset to compare with EMLight's work, but I got some problems about the input file structure in the training and testing stage. And I have not solve these problems now...

**Comment by liuyuwan233** [comment]
> > Hi!
> > ```
> > 1. In the paper, you mentioned 'Detailed network structure of neural projector and the training settings are provided in the supplementary file.', but I can not fild the supplementary file. Would you like to tell me where is the supplementary file?
> > 
> > 2. What's more, I tried to train my own dataset with your code for comparison, but I don't know the original file structure so I got some problems. Could you tell me the structure of the original file and the format of the images in the folder?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thank you very much!
> 
> Hi!
> 
> I want follow EMLight's work, but i can't use LavalInDoor dataset, because professor Jean-François Lalonde told me that their server was broke down since bout 2 months ago. I wonder that what other dataset you want to use to train?
> 
> Thanks!

Hi!
I wanted to train my own dataset to compare with EMLight's work, but I got some problems about the input file structure in the training and testing stage. And I have not solve these problems now...

**Comment by jxl0131** [comment]
> 

Hi!

You seem to be a chinese student, so am i. I know something about the input file structure, can i get your wechat?

Thanks!

**Comment by jxl0131** [comment]
> > > Hi!
> > > ```
> > > 1. In the paper, you mentioned 'Detailed network structure of neural projector and the training settings are provided in the supplementary file.', but I can not fild the supplementary file. Would you like to tell me where is the supplementary file?
> > > 
> > > 2. What's more, I tried to train my own dataset with your code for comparison, but I don't know the original file structure so I got some problems. Could you tell me the structure of the original file and the format of the images in the folder?
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Thank you very much!
> > 
> > 
> > Hi!
> > I want follow EMLight's work, but i can't use LavalInDoor dataset, because professor Jean-François Lalonde told me that their server was broke down since bout 2 months ago. I wonder that what other dataset you want to use to train?
> > Thanks!
> 
> Hi! I wanted to train my own dataset to compare with EMLight's work, but I got some problems about the input file structure in the training and testing stage. And I have not solve these problems now...

Hi!

You seem to be a chinese student, so am i. I know something about the input file structure, can i get your wechat?

Thanks!

**Comment by fnzhan** [comment]
For data structure, https://github.com/fnzhan/EMLight/blob/025f83dfb528d9211c45050237b9100647e7e622/RegressionNetwork/data.py#L23

crop_dir is the folder of cropped hdr images of a local region.
gt_dir is the processed ground truth with distribution_representation.py in /RegressionNetwork/representation
