### ISSUE TITLE
Running inference only?

### ISSUE THREAD

**Issue by DaLizardWizard** [fnzhan/EMLight#27]
I have been trying to get the code to work on generate a rough HDRI from an image input but have had no luck so far, I have downloaded the pretrained model but I am not entirely sure where to start. Can anyone help me?

**Comment by fnzhan** [comment]
Please check EMLight/RegressionNetwork/test.py.

But if you are using images different from Laval Indoor dataset, you may need to train the model with your own data thanks to the domain gap.
